name: Build firmware

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Add ARM GCC path for Windows
    - name: Add ARM GCC to PATH
      run: echo "C:\Program Files (x86)\GNU Arm Embedded Toolchain\10 2021.10\bin" >> $env:GITHUB_PATH

    # Build
    - name: Build
      run: |
        make clean
        make


    - name: Upload firmware files
      uses: actions/upload-artifact@v4
      with:
        name: bootloader-build
        path: |
          build/*.elf
          build/*.hex
          build/*.bin
